---
- name: Install supervisor
  apt: pkg=supervisor
       state=latest
       update_cache=yes
  sudo: yes

- name: Confiure supervisor
  template: src=supervisord.conf.j2
            dest=/etc/supervisor/supervisord.conf
  notify: Reload supervisor
